title: My Portfolio
description: "Welcome to my portfolio site showcasing my projects and skills."
baseurl: ""  # Leave blank if deploying at the root level
url: "https://<your-username>.github.io"  # Your GitHub Pages URL

author:
  name: "Your Name"
  email: "your-email@example.com"

theme: "architect"

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

# Social media links
social:
  github: "https://github.com/your-username"
  linkedin: "https://www.linkedin.com/in/your-linkedin/"
